### ISSUE TITLE
Examples of using sub objects

### ISSUE THREAD

**Issue by ADringer** [lucabriguglia/Kledex#61]
Hi,

Been having a play around with Kledex and really like it so far! However I'm having a little trouble working out the best practice to handle sub objects on my aggregate. Using the example of products that you have, the criteria would be something like:

1. A product can have many reviews.
2. A review has a 'score' property which is an int
3. A review can be added to the product through a command
4. A specific review can have it's score updated

How would we go about implementing this? I can see there is an `Entity` class which I think `Review` should extend but haven't seen any specific examples. I would have thought that the `Review` should be responsible for it's own events but I don't believe you can add events from an `Entity` class.

Any examples/hints would be greatly appreciated,

Thanks

**Comment by lucabriguglia** [comment]
Hi @ADringer,

I think you've got two options here. The first one is to keep Review as "Entity" within the aggregate where Product is the aggregate root. In that case the event "ReviewAdded" belongs to the Product aggregate. The second option is for the Review to be an aggregate root itself and have just the product id as reference to the product aggregate. In that case all events would belong to the review aggregate.

Not sure which one is the best option for you because I don't know your domain but as simple rule I always try to keep the aggregates as small as possible.

**Comment by andreujuanc** [comment]
Agree with @lucabriguglia comment. Keep the aggregates small.
Just make Review as an aggregate and have the read model store the calculated score.
So actually the review is not added to the product, but it just has a reference to it.

So: 

1. A product can have many reviews. ✔️  The readmodel can have a FK (if using relational for example) 
2. A review has a 'score' property which is an int ✔️ Calculate it in Review aggregate and store result in readmodel
3. A review can be added to the product through a command ✔️ 
4. A specific review can have it's score updated ✔️ Also a command that updates the score.

**Comment by ADringer** [comment]
Hi  guys,

thanks for your replies! I understand and agree with you from a implementation point of view, but feel that this isn't necessarily the best practice for DDD. Let me try another example:

Say you have a User aggregate, and a user can have multiple addresses. Only one of these addresses can be flagged as 'primary' at a time. I think you should have to go through the User aggregate and try to set the address through this and have the business logic in the domain, not outside it.

To me, it seems nicer to go through the aggregate, call some kind of `SetPrimary()` method which within the domain will add the events `AddressNotPrimary` on the existing one and `AddressMadePrimary` on the new one. 

The alternative to the above flow if using Address aggregates would be to retrieve the address that is currently  primary, add the event `AddressNotPrimary` and then get the address that is to be primary and add `AddressMadePrimary`. This seems like too much orchestration within the handler which should be in the business logic.

Also for consideration, how would you go about checking if an address is unique for a user? It's nicer going through the User aggregate, call `AddAddress()` which compares here, rather than retrieving all the addresses by user and then comparing them in the handler.

Hopefully I've explained my thoughts ok! But ultimately trying to keep it DDD and have the logic kept within the aggregate that the data belongs to.

Thanks

**Comment by lucabriguglia** [comment]
I agree with you that it would be nicer, but again it depends on your aggregate. In your first example you have products. What's already in the product aggregate? You might have product which is the aggregate root, then you might have variants, categories, prices, reviews, etc. It may get too big at some point and it would be better to re-design the bounded context.

**Comment by andreujuanc** [comment]
We have something very similar than your example, and yes in our case we do that logic in the user itself, but we also have a rule in which if an aggregate gets too big we sitdown and rethink the whole domain again, to have this issues with least frequency as possible (we're all humans and this can happen).

If the logic for the address is so complex as you described (and it's probably even more since it's just an example), that by itself can be it's own aggregate and that will save you a lot of time, specially because with event sourcing you do **not** want to change the "schema" as much as possible, so if you predict that it will grow in complexity, consider making it an aggregate.

IMHO, DDD is not a rule, nor a strict law. But a way of thinking and describing your business as code as close as you **can**. And compromises can be made.

**Comment by lucabriguglia** [comment]
Hi guys I'm closing this issue as there's not been any activity for a while.
