### ISSUE TITLE
[Question] How is the concurrency supported?

### ISSUE THREAD

**Issue by xaviersolau** [lucabriguglia/Kledex#81]
Hello,
How is supported concurrency? I mean if I want to process two commands on the same aggregate ?
Regards

**Comment by lucabriguglia** [comment]
Hi,
there is an option to check for the expected version.
In the domain command you can set the expected version number.
If the actual version is different from the expected version a concurrency exception is thrown.
Is this answer your question?

**Comment by xaviersolau** [comment]
Ok but when are we supposed to set the expected version exactly? in the command handler when the aggregate is loaded?

**Comment by lucabriguglia** [comment]
When the command is created before using the dispatcher.
Imagine you have a web app and a mobile app and two commands are sent to the API at the same time. Both apps are expecting the aggregate to be on version let's say 4 and the second command to finish the work would find the version to be 5 and therefore the state is invalid because the command was based on version 4.

**Comment by xaviersolau** [comment]
Do you mean that I have to load the aggregate (in order to get the current version) before I can create a command?

**Comment by lucabriguglia** [comment]
If you want to use the expected version functionality in oprder to prevent concurrency issues you need somehow to provide the version number which might even come from the read model so you won't need to load the whole aggregate.

**Comment by xaviersolau** [comment]
Here is the way I would like to use it. Please tell me if I am doing it wrong or if I am missing something.

Let's take an example with an “account” with a Sold property and a “debitCommand” with an Amount property:

All is coded in the debit command handler:

1: Load aggregate
```csharp
var account = await _repository.GetByIdAsync(debitCommand.AggregateRootId);
```
2: Check the account is known
```csharp
if (account == null)
{
    throw new ApplicationException("Account not found.");
}
```
3: Check the command can be applied (based on the loaded aggregate version) in other words check if the sold account is bigger than the debit amount. (By the way is it the best place where to process this check or should it be in account.Debit() method implementation?)
```csharp
if (account.Sold < debitCommand.Amount)
{
    throw new ApplicationException("Account sold too low.");
}
```
4: Update the command expected version
```csharp
debitCommand.ExpectedVersion = account.Version + 1 ;
```
I am not really happy with the way of doing it:
- Is there a better way to compute the next version?
- Is the command supposed to be immutable?

5: Apply the command to the aggregate
```csharp
account.Debit(debitCommand.Amount) ;
```
6: Return command resulting events
```csharp
return account.Events;
```

**Comment by lucabriguglia** [comment]
There is an error in your implementation, the expected version should be `account.Version` and not `account.Version + 1` also my concern is related to the fact that a command could be based on a stale version. Let's assuming that 2 users load the same aggregate on a particular UI and the version for both of them is **4**. 
The first user sends a command and your implementation would be correct (after removing the `+ 1`).
The second user sends another command and the expected version set by the handler would be **5**, because the first event would have been already saved. It is not correct because the user modified the aggregate based on version **4** and not **5**, therefore it would potentially override some changes of the first user without even knowing what they are.

**Comment by xaviersolau** [comment]
Ok thanks for the `+1`.

My point about the concurrent access is that if my API is receiving two commands (debit 10) concurrently, I will have two thread handling the commands and my account sold is 15.

Let's say that I have the following operations:
Thread 1: load aggregate in version 4 (sold = 15)
Thread 2: load aggregate in version 4 (sold = 15)
Thread 1: check sold 15>10 and set the expected version 4
Thread 2: check sold 15>10 and set the expected version 4
Thread 1: save debit event successfully with expected version 4.
Thread 2: fail to save the event because of the expected version is 4 instead of 5 (throw exception).

In this case the thread 2 will eventually retry the command (automatically or with a user action) and load the new version of aggregate and see that the account sold is too low.

In this case, this is my expected behavior. Don't you agree ?

**Comment by lucabriguglia** [comment]
Yes, I agree that in your specific scenario is fine because you are covering it in your business logic :-)

**Comment by xaviersolau** [comment]
Ok thanks for your answers! I will try with this implementation then....
Regards

**Comment by lucabriguglia** [comment]
No worries, please let me know if you have any other questions!
